### ISSUE TITLE
Profiler error when increasing PROFILER_MAX_DEPTH

### ISSUE THREAD

**Issue by miki725** [jazzband/django-debug-toolbar#1004]
With default profiler max depth of 10, everything works as expected. However when increasing that number to higher threshold starting to get these:

```python
Traceback (most recent call last):
  File "/www/env/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/www/env/lib/python2.7/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/www/dtweb/dtweb/wsgi.py", line 79, in application
    return get_django_wsgi_application()(environ, start_response)
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/www/env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/www/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/www/env/lib/python2.7/site-packages/debug_toolbar/decorators.py", line 15, in inner
    return view(request, *args, **kwargs)
  File "/www/env/lib/python2.7/site-packages/debug_toolbar/views.py", line 21, in render_panel
    content = panel.content
  File "/www/env/lib/python2.7/site-packages/debug_toolbar/panels/__init__.py", line 96, in content
    return render_to_string(self.template, self.get_stats())
  File "/www/env/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/www/env/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/www/env/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/www/env/lib/python2.7/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/www/env/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/www/env/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/www/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/www/env/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/www/env/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/www/env/lib/python2.7/site-packages/django/template/base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "/www/env/lib/python2.7/site-packages/django/template/base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "/www/env/lib/python2.7/site-packages/django/template/base.py", line 911, in _resolve_lookup
    current = current()
  File "/www/env/lib/python2.7/site-packages/debug_toolbar/panels/profiling.py", line 79, in func_std_string
    file_path, file_name = file_name.rsplit(os.sep, 1)
ValueError: need more than 1 value to unpack
```

I assume since it works with lower depth, configuration is good. Is this a known bug or might be something off in my config?

**Comment by miki725** [comment]
adding a breakpoint here is the content of `self.func` right before the exception:

```python
(Pdb++) self.func
('<string>', 1, '<lambda>')
```

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this one has shipped and can be closed.

The `ValueError: need more than 1 value to unpack` from `func_std_string` in `debug_toolbar/panels/profiling.py` was fixed in commit [`0d0132b3`](https://github.com/django-commons/django-debug-toolbar/commit/0d0132b3) ("Fix crash in profiling when no directory name found", Yannick Jost, 2018-04-19), which landed about five months after this issue was opened.

- The crash site referenced in your traceback (`file_path, file_name = file_name.rsplit(os.sep, 1)`) is now guarded at [`debug_toolbar/panels/profiling.py:72-76`](https://github.com/django-commons/django-debug-toolbar/blob/main/debug_toolbar/panels/profiling.py#L72-L76): it checks `len(split_path) > 1` before unpacking and falls back to `file_path = "<module>"` when no `os.sep` is present.
- A quick `git log --all -G "split_path" -- debug_toolbar/panels/profiling.py` on the current repo shows the same commit `0d0132b3` as the original fix.

If you're still hitting profiler crashes on a current toolbar version (the cProfile + Python 3.12 case in #1875 is a separate, ongoing investigation), a fresh issue with a 2026-era traceback would be easier to act on. Otherwise, would you mind closing this out?

---

*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `main` branch.*
