### ISSUE TITLE
Windows, critical problem with omit_path

### ISSUE THREAD

**Issue by mmmcorpsvit** [jazzband/django-debug-toolbar#1080]
i work in windows and use: https://github.com/mirumee/saleor
but when run with debug toolbar sometimes i have many many times repeat logs like this (load long, around 15-20 seconds!!!):

```
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13E61690>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
127.0.0.1 - - [27/Aug/2018 15:20:07] "GET /media/__sized__/products/saleor/static/placeholders/books/book-01_jWYVkdr-crop-c0-5__0-5-255x255-70.jpg HTTP/1.1" 200 -
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13DDBEA0>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13DDBEA0>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13DDBEA0>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13DDBEA0>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13DDBEA0>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13DDBEA0>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x12B63120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x139120C0>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
127.0.0.1 - - [27/Aug/2018 15:20:07] "GET /media/__sized__/products/saleor/static/placeholders/books/book-05_NKaLcWw-crop-c0-5__0-5-255x255-70.jpg HTTP/1.1" 200 -
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13912060>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13912060>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x13912060>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x126AA810>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x126AA810>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x126AA810>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x126AA810>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
127.0.0.1 - - [27/Aug/2018 15:20:07] "GET /en/cart/summary/ HTTP/1.1" 200 -
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x126AA810>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object omit_path.<locals>.<genexpr> at 0x126AA810>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\utils.py", line 53, in <genexpr>
    e = any(path.startswith(hidden_path) for hidden_path in hidden_paths)
SystemError: error return without exception set
Exception ignored in: <generator object Apps.is_installed.<locals>.<genexpr> at 0x13D50BD0>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\django\apps\registry.py", line 233, in <genexpr>
    return any(ac.name == app_name for ac in self.app_configs.values())
SystemError: error return without exception set
Exception ignored in: <generator object contrasting_color_generator at 0x12D56120>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\panels\sql\utils.py", line 59, in contrasting_color_generator
    yield rgb_to_hex(rgb)
SystemError: error return without exception set
Exception ignored in: <generator object contrasting_color_generator at 0x12DFEE40>
Traceback (most recent call last):
  File "G:\Dev\tadshop\site\venv\lib\site-packages\debug_toolbar\panels\sql\utils.py", line 39, in contrasting_color_generator
    def contrasting_color_generator():
```

i try fix problem ugly just:
```
def omit_path(path):
    return True
```
and now can work normal, i dont understand how this fix correct and what do this function, need you help)

**Comment by matthiask** [comment]
The `omit_path` function has been removed/replaced in cd4c7480c52cc90d9fda4d7a66e89a6e75266d33 so I'm going to close this, hoping that the underlying bug has been fixed as a side effect.
