### ISSUE TITLE
django.template:DEBUG Exception while resolving variable 'similar_count' in template 'debug_toolbar/panels/sql.html'

### ISSUE THREAD

**Issue by hnykda** [jazzband/django-debug-toolbar#1374]
Hi,

I am facing a weird stacktrace when using debug_toolbar. Basically, when locally developing and using `django_toolbar`, for every request, I get a *long* stacktrace originating in base templates. It starts like this:

```
20201005 09:31:21:django.template:DEBUG Exception while resolving variable 'similar_count' in template 'debug_toolbar/panels/sql.html'.
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'SQLPanel' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'similar_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'similar_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'similar_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [similar_count] in 
```

and I don't really know where to start nor I am able to generate a minimal example. Can someone give me please some pointers what to try? Thanks

**Comment by tim-schilling** [comment]
Could you create a basic TemplateView that does nothing and see if that reproduces it? If it does, then slowly remove middleware that may impact the template's context and template context processors. That may help narrow down your search for the root cause.

My guesses would be a weird query that the SQL panel isn't handling well or context used to render a template is being manipulated in a way the toolbar isn't built to handle.

**Comment by hnykda** [comment]
Thanks. It does on a basic view too. I will try removing those middlewares
and templates context processors, thanks. But it's an almost fresh
project so not sure what could be wrong.

**Comment by Javrd** [comment]
I've had same problem. I'm using channels and it stop if I use `--noasgi` option with `runserver` (that is not cool as websockets stop working) or if I delete `debug_toolbar.panels.sql.SQLPanel` from `DEBUG_TOOLBAR_PANELS` in settings:
```python
DEBUG_TOOLBAR_PANELS = [
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    # "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
    "debug_toolbar.panels.profiling.ProfilingPanel",
]
```

**Comment by iacobfred** [comment]
I'm also having this problem. Removing `SQLPanel` from `DEBUG_TOOLBAR_PANELS` gets rid of the error, but I need to be able to use the SQL panel.....

**Comment by Hassanzadeh-sd** [comment]
add this to url.py

```
from django.conf import settings
from django.conf.urls import include

...

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
```

**Comment by matthiask** [comment]
The import shouldn't be necessary anymore. Just

```python
if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
```

**Comment by merwan** [comment]
If that can help, I get the same kind of error when running my application with gunicorn.
The error disappear when running the application with the Django development web server

**Comment by tim-schilling** [comment]
@merwan if you can create a reproducible environment we can help look into it.

**Comment by Jdsleppy** [comment]
I can reproduce in a brand new Django project, steps as follows using `uv` to create a Python 3.13 environment:

```
uv init debug-toolbar-1374 --python=3.13
cd debug-toolbar-1374/
uv add django django-debug-toolbar
rm main.py  # hello world script created by uv
uv run django-admin startproject repro .
```

```python
# repro/settings.py
INTERNAL_IPS = ["127.0.0.1"]
INSTALLED_APPS = [
    "debug_toolbar",
    ...
]
MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    ...
]
TEMPLATES = [
    {
        ...
        "DIRS": [BASE_DIR / "templates"],
        ...
    },
]

from django.utils.log import DEFAULT_LOGGING

LOGGING = DEFAULT_LOGGING
LOGGING["handlers"]["console"]["level"] = "DEBUG"
LOGGING["loggers"]["django"]["level"] = "DEBUG"
```


```python
# repro/urls.py
from django.urls import path
from django.shortcuts import render
from debug_toolbar.toolbar import debug_toolbar_urls


def hello_world(request):
    return render(request, "index.html")


urlpatterns = [
    path("", hello_world),
] + debug_toolbar_urls()
```

```html
<!--templates/index.html-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <p>Hello, world</p>
  </body>
</html>
```

```
uv run python manage.py runserver
```

Logs from visiting `http://127.0.0.1:8000/`:

```
[01/May/2025 15:30:15] "GET / HTTP/1.1" 200 13608
[01/May/2025 15:30:15] "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 14803
[01/May/2025 15:30:15] "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 29444
[01/May/2025 15:30:15] "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4692
[01/May/2025 15:30:15] "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
                                               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/django/urls/resolvers.py", line 705, in resolve
    raise Resolver404({"tried": tried, "path": new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLPattern ''>], [<URLResolver <module 'debug_toolbar.urls' from '/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/debug_toolbar/urls.py'> (djdt:djdt) '^__debug__/'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/django/template/base.py", line 890, in _resolve_lookup
    raise TypeError
TypeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/django/template/base.py", line 901, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/django/template/base.py", line 907, in _resolve_lookup
    current = current[int(bit)]
                      ~~~^^^^^
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/django/template/base.py", line 914, in _resolve_lookup
    raise VariableDoesNotExist(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )  # missing attribute
    ^
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'debug_toolbar.urls' from '/home/joel/Code/debug-toolbar-1374/.venv/lib/python3.13/site-packages/debug_toolbar/urls.py'> (djdt:djdt) '^__debug__/'>
```

I'll dig in to see if anything pops out to me.

I could share a zip archive of these files, but I don't know how happy people are to open random zips.

**Comment by matthiask** [comment]
Something like this would avoid these warnings in the request panel:

```
diff --git i/debug_toolbar/utils.py w/debug_toolbar/utils.py
index f4b3eac3..9ae2cead 100644
--- i/debug_toolbar/utils.py
+++ w/debug_toolbar/utils.py
@@ -225,7 +225,7 @@ def sanitize_and_sort_request_vars(
     request data with sensitive values redacted.
     """
     if not isinstance(variable, (dict, QueryDict)):
-        return {"raw": variable}
+        return {"raw": variable, "list": None}
 
     # Get sorted keys if possible, otherwise just list them
     keys = _get_sorted_keys(variable)
@@ -236,7 +236,7 @@ def sanitize_and_sort_request_vars(
     else:
         result = _process_dict(variable, keys)
 
-    return {"list": result}
+    return {"list": result, "raw": None}
 
 
 def _get_sorted_keys(variable):
```

I'm not sure we care that much about missing variables in Django templates. I know there are people who want the Django template language to fail on missing variables, but `string_if_invalid` defaults to the empty string and that's probably what most people use: 

> If you use a variable that doesn’t exist, the template system will insert the value of the string_if_invalid option, which is set to '' (the empty string) by default.

https://docs.djangoproject.com/en/5.2/ref/templates/language/#variables

I'm not against someone submitting a PR which adds the "missing" keys to our contexts, I just don't want to hunt down all those places myself (and nor do I want to write the tests for that)

**Comment by tim-schilling** [comment]
Forwarding @talkingseed's [report from here](https://github.com/django-commons/django-debug-toolbar/issues/2150#issue-3197779882) 

> ### Environment
> - Django version: 5.1.x
> - Django Debug Toolbar Version: 4.4.6
> - Python version: 3.12
> - Database: PostgreSQL
> 
> ### Description
> When using Django Debug Toolbar in development, the console logs are flooded with template variable resolution errors, making the logs unusable. The errors occur repeatedly for every request.
> 
> ### Error Messages
> 
> 1. **SQL Panel Errors:**
> ```python
> Exception while resolving variable 'starts_trans' in template 'debug_toolbar/panels/sql.html'.
> django.template.base.VariableDoesNotExist: Failed lookup for key [starts_trans] in {'vendor': 'postgresql', ...}
> 
> Exception while resolving variable 'ends_trans' in template 'debug_toolbar/panels/sql.html'.
> django.template.base.VariableDoesNotExist: Failed lookup for key [ends_trans] in {'vendor': 'postgresql', ...}
> 
> Exception while resolving variable 'similar_count' in template 'debug_toolbar/panels/sql.html'.
> django.template.base.VariableDoesNotExist: Failed lookup for key [similar_count] in {'vendor': 'postgresql', ...}
> 
> Exception while resolving variable 'duplicate_count' in template 'debug_toolbar/panels/sql.html'.
> django.template.base.VariableDoesNotExist: Failed lookup for key [duplicate_count] in {'vendor': 'postgresql', ...}
> 
> Exception while resolving variable 'in_trans' in template 'debug_toolbar/panels/sql.html'.
> django.template.base.VariableDoesNotExist: Failed lookup for key [in_trans] in {'vendor': 'postgresql', ...}
> ```
> 
> 2. **Request Panel Errors:**
> ```python
> Exception while resolving variable 'raw' in template 'debug_toolbar/panels/request.html'.
> django.template.base.VariableDoesNotExist: Failed lookup for key [raw] in {'list': []}
> ```
> 
> 3. **Templates Panel Errors:**
> ```python
> AttributeError: 'dict' object has no attribute 'ends_trans'
> AttributeError: 'dict' object has no attribute 'starts_trans'
> ```
> 
> ### Expected Behavior
> Debug toolbar should work without flooding the console with template variable resolution errors.
> 
> ### Actual Behavior
> Every request generates dozens of template variable errors in the console, making development logs unusable. The debug toolbar still functions, but the noise in the logs makes it difficult to see actual application errors or debug output.
> 
> ### Steps to Reproduce
> 1. Install Django Debug Toolbar in a Django 5.1 project
> 2. Configure it according to the documentation
> 3. Make any request to the application
> 4. Observe the console output filled with template variable errors
> 
> ### Workaround Attempted
> Had to disable SQL and Templates panels to reduce log noise:
> ```python
> DEBUG_TOOLBAR_PANELS = [
>     'debug_toolbar.panels.history.HistoryPanel',
>     'debug_toolbar.panels.versions.VersionsPanel',
>     'debug_toolbar.panels.timer.TimerPanel',
>     'debug_toolbar.panels.settings.SettingsPanel',
>     'debug_toolbar.panels.headers.HeadersPanel',
>     'debug_toolbar.panels.request.RequestPanel',
>     # 'debug_toolbar.panels.sql.SQLPanel',  # Disabled due to errors
>     'debug_toolbar.panels.staticfiles.StaticFilesPanel',
>     # 'debug_toolbar.panels.templates.TemplatesPanel',  # Disabled due to errors
>     'debug_toolbar.panels.cache.CachePanel',
>     'debug_toolbar.panels.signals.SignalsPanel',
>     'debug_toolbar.panels.logging.LoggingPanel',
>     'debug_toolbar.panels.redirects.RedirectsPanel',
>     'debug_toolbar.panels.profiling.ProfilingPanel',
> ]
> ```
> 
> ### Possible Cause
> It appears that the SQL panel template expects certain attributes (`starts_trans`, `ends_trans`, `similar_count`, `duplicate_count`, `in_trans`) on query dictionaries that aren't being provided by the panel's context generation.
> 
> ### Additional Context
> - Running behind nginx proxy with SSL
> - Using PostgreSQL database
> - The debug toolbar still functions correctly despite the errors
> - The errors only appear in console logs, not in the browser
> 
> Would appreciate any guidance on resolving this issue or if this is a known compatibility issue with Django 5.1.
