### ISSUE TITLE
Incompatible with Django 4.2

### ISSUE THREAD

**Issue by bh** [jazzband/django-debug-toolbar#1754]
```
Traceback (most recent call last):
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 230, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/utils/functional.py", line 266, in inner
    self._setup()
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/utils/functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/sessions/backends/base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 230, in execute
    return self._record(self.cursor.execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bh/devel/wm/marketplaces/app/.venv/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 150, in _record
    initial_conn_status = conn.status
                          ^^^^^^^^^^^
AttributeError: 'Connection' object has no attribute 'status'

```
`poetry show | grep -e django -e psycopg `
```
django               4.2       A high-level Python web framework that encou...
django-cacheops      7.0       A slick ORM cache with automatic granular ev...
django-chartjs       2.3.0     Django Chart.js and Hightchart ajax views
django-countries     7.5.1     Provides a country field for Django models.
django-debug-toolbar 3.8.1     A configurable set of panels that display va...
django-environ       0.10.0    A package that allows you to utilize 12facto...
django-extensions    3.2.1     Extensions for Django
django-filter        23.1      Django-filter is a reusable Django applicati...
django-fsm           2.8.1     Django friendly finite state machine support.
django-money         3.0.0     Adds support for using money and currency fi...
django-ordered-model 3.7.4     Allows Django models to be ordered and provi...
djangorestframework  3.14.0    Web APIs for Django, made easy.
psycopg              3.1.8     PostgreSQL database adapter for Python
psycopg-c            3.1.8     PostgreSQL database adapter for Python -- C ..

```
Python 3.11.2

**Comment by elapouya** [comment]
I confirm, I have this problem too : Python 3.11.2 / Django 4.2 / psycopg-binary 3.1.8

**Comment by dthorell** [comment]
Having the same issue with current pypi release (3.8.1), direct from GitHub main branch works. So probably a new release is needed

**Comment by adamchainz** [comment]
Yes, this was fixed in #1736.

**Comment by matthiask** [comment]
django-debug-toolbar 4.0 should contain a fix for this. Thanks!
