### ISSUE TITLE
HTMX post request causes `AttributeError: 'str' object has no attribute 'items'`

### ISSUE THREAD

**Issue by bittner** [jazzband/django-debug-toolbar#1803]
I use HTMX with [django-htmx](https://django-htmx.readthedocs.io/), which plays well with _django-debug-toolbar_ until I use a HTMX-triggered POST request.

The Django HTMX docs suggests to [configure the CSRF token via a header](https://django-htmx.readthedocs.io/en/latest/tips.html) for this to work. It looks likes this causes an invalid request object of type `str` to be passed, which causes trouble for the debug toolbar.

## Symptoms

```python
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/.../venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 69, in __call__
    panel.generate_stats(request, response)
  File "/home/.../venv/lib/python3.10/site-packages/debug_toolbar/panels/headers.py", line 51, in generate_stats
    self.response_headers = dict(sorted(response.items()))
AttributeError: 'str' object has no attribute 'items'
```

When I add a guard at line 51 to make the code work, e.g.

```python
        if type(response) is HttpResponse:
```

... then I get the next related problem:

```python
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/.../venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 69, in __call__
    panel.generate_stats(request, response)
  File "/home/.../venv/lib/python3.10/site-packages/debug_toolbar/panels/history/panel.py", line 77, in generate_stats
    "status_code": response.status_code,
AttributeError: 'str' object has no attribute 'status_code'
```

... which, if bypassed, continues in the middleware, e.g.

```python
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/.../venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 78, in __call__
AttributeError: 'str' object has no attribute 'headers'
Internal Server Error: /query-input-valid/
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/.../venv/lib/python3.10/site-packages/debug_toolbar/middleware.py", line 78, in __call__
AttributeError: 'str' object has no attribute 'headers'
```

## Further Analysis

When I run my project in production mode (i.e. `DJANGO_DEBUG=false`, `DJANGO_SECRET_KEY=<random>`, etc.) I do get an error that suggests that there is something misconfigured with my current state of affairs:

```python
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/.../venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/home/.../venv/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
```

## What next?

I'm not sure whether _django-debug-toolbar_ should be able to deal with such a situation instead of falling over. I'm happy to hear opinions.

I'd also be happy to know whether other developers using HTMX have seen this very problem, too.

## Related Code Locations

1. [debug_toolbar.panels.headers](https://github.com/jazzband/django-debug-toolbar/blob/4.1/debug_toolbar/panels/headers.py#L49) (line 49)
2. [debug_toolbar.panels.history.panel](https://github.com/jazzband/django-debug-toolbar/blob/4.1/debug_toolbar/panels/history/panel.py#L77) (line 77)
3. [debug_toolbar.middleware](https://github.com/jazzband/django-debug-toolbar/blob/4.1/debug_toolbar/middleware.py#L77) (line 77, etc.)

**Comment by tim-schilling** [comment]
It seems like the response is a string and not a HttpResponse instance. Are
you sure your view is returning the proper type?

**Comment by bittner** [comment]
> It seems like the response is a string and not a HttpResponse instance.

This is true. Because I wanted to return a status (context: to enable a button on a form) I made the view return just the value. That's certainly a programmer mistake.

So, is that fine that this makes the debug toolbar fall over? Or should we better handle this gracefully?

**Comment by tim-schilling** [comment]
A django view needs to return a HttpResponse. It's not a toolbar specific
concern

**Comment by bittner** [comment]
Has no-one ever asked for the toolbar to say, _"Hey, the response is invalid"_, or, _"Hey, there's something wrong with your request"_?

But, yeah, the application would fall over anyway, even if the toolbar inspected the response more carefully. It wouldn't be much of a usability gain. Agreed.

**Comment by tim-schilling** [comment]
I don't think it has been asked of the toolbar. But there are many things
in the request process that could convert something to a string or invalid
type.

Theoretically it's possible to have a middleware that evaluates the views
response to make sure it conforms, but that doesn't mean the subsequent
middlewares would leave the response alone.

**Comment by tim-schilling** [comment]
It could be reasonable to have it check the type of response before
attempting to use it, but that's atypical of python in my experience.

**Comment by installwindows** [comment]
My problem was that I had two functions: `get_something` and `get_something_api`. The first would return a string and the other was returning a django-rest-framework `Response`. I mistakenly used the first function `get_something` in my _urls.py_ instead of `get_something_api`.
