### ISSUE TITLE
Profiler raises ValueError in Python 3.12 due to cPro

### ISSUE THREAD

**Issue by anorthall** [jazzband/django-debug-toolbar#1875]
Enabling the profiling panel in Python 3.12 and Django 5.0.1 causes the following exception:

```
   File "/usr/local/lib/python3.12/site-packages/debug_toolbar/panels/profiling.py", line 144, in process_request
     return self.profiler.runcall(super().process_request, request)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/cProfile.py", line 109, in runcall
     self.enable()
 ValueError: Another profiling tool is already active
```

This is due to a change in Python 3.12: https://github.com/python/cpython/issues/110770

There is also some relevant discussion of the same issue over on the django-silk repo which may be helpful in finding a way forward: https://github.com/jazzband/django-silk/issues/682

**Comment by elineda** [comment]
Hello, 

Can you give me step for reproduce the bug. I try enable the profiling panel with django 5.0.1 and python 3.12.1, I have not the problem.

**Comment by matthiask** [comment]
It happens to me as well, but only intermittently. Maybe reloading a few times, enabling and disabling the profiler panel using the checkbox and/or restarting the development server works when trying to reproduce the problem?

**Comment by ddkasa** [comment]
This is issue is happening for me as well, but can't seem to determine what's causing the issue.

Tried to go through all the installed apps and no conflicts seem to resolve it and tried with 2 browsers as well.

Django 5.0.2 / Python 3.12.1

What's the progress on this or are there any updates on this?

Working the profile panel disabled by default in settings for now.

**Comment by mfosterw** [comment]
I don't have a solution, but I have found a way to consistently produce the bug. When running a NextJS app that depends on a django api with the vscode debugger, every hard refresh from the nextjs frontend results in this error on the backend. I have no idea if the vscode debugger is contributing to the error, but note that I am running both the frontend and the backend from vscode. I hope this can be useful for someone to eventually debug the problem! (In the meantime, I'll be disabling the panel).

**Comment by elineda** [comment]
Ok seem the problem occurs only the two requests are send on the runserver in the same times. Using a debuger like pycharm one is not necessary.
That's strange because runserver only do one request at the time. Need to find one profiler open even if the other is not finished

**Comment by elineda** [comment]
I propose to add a note in installation.rst or tip.rst. I don't know if it's possible by adding something in the debug toolbar to disable the multitreading.

**Comment by ddkasa** [comment]
@elineda Adding _--nothreading_ to the  **runserver** command does seem to resolve the issue for me.

I am running my development server through Uvicorn though, so I am curious if you know know a solution for that as well?

**Comment by elineda** [comment]
> @elineda Adding _--nothreading_ to the **runserver** command does seem to resolve the issue for me.
> 
> I am running my development server through Uvicorn though, so I am curious if you know know a solution for that as well?

gunicorn -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8010  configuration.asgi:application

**Comment by tim-schilling** [comment]
> I propose to add a note in installation.rst or tip.rst. I don't know if it's possible by adding something in the debug toolbar to disable the multitreading.

@elineda What do you think about putting it as an admonition/warning in the Profiling panel area of the docs? I think I have a slight preference to that, but would also be okay with it going in tip.rst. I'd prefer to keep the installation docs as short as possible.

**Comment by elineda** [comment]
I'm ok to add a note in profiling. If you have a problem with it you will check (I hope) the panel doc before complain.

**Comment by tim-schilling** [comment]
Agreed

**Comment by matthiask** [comment]
I wonder if it would be possible to add a counter variable which tracks the number of currently active profiling sessions; the profiler would only be activated when incrementing from zero and would only be deactivated when decrementing to zero?

**Comment by tim-schilling** [comment]
I think we'd have to count that across threads.

**Comment by elineda** [comment]
> I wonder if it would be possible to add a counter variable which tracks the number of currently active profiling sessions; the profiler would only be activated when incrementing from zero and would only be deactivated when decrementing to zero?

in that case what we do when another request come, we do it without profiler or we wait ?

**Comment by tim-schilling** [comment]
> > I think we'd have to count that across threads.
> 
> we can use cache for that.

Yes, that's an option. It would create a dependency on the CACHES setting being configured to run at least this particular panel. That's not ideal.

**Comment by elineda** [comment]
with async compatibilty we will  need a cache, for the same reason isn't ?

**Comment by agusmakmun** [comment]
So the configs become:

```python
DEBUG_TOOLBAR_CONFIG = {
    "DISABLE_PANELS": [
        "debug_toolbar.panels.profiling.ProfilingPanel",  # additional one
        "debug_toolbar.panels.redirects.RedirectsPanel",
    ],
    "SHOW_TEMPLATE_CONTEXT": True,
}
```

https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#toolbar-options

It's fixed for my as `uvicorn` doesn't have `--nothreading` parameter, especially for who use the django-cookie-cutter.

**Comment by Mogost** [comment]
Perhaps I'm too naive. But why can't we just catch it and treat it as an exception?

https://github.com/jazzband/django-debug-toolbar/blob/b5cf78460d8a36d83ff8aadb97f01a6346527632/debug_toolbar/panels/profiling.py#L146

```python
try:
	return self.profiler.runcall(super().process_request, request)
except ValueError:
	logger.warning(...)
	 return super().process_request(request) 
```

**Comment by tim-schilling** [comment]
I'm unable to reproduce this now. Can anyone else?

**Comment by amureki** [comment]
@tim-schilling hey Tim! I just tried to enable the profiling panel again, and I can confirm that I am still experiencing it:


0. Python 3.14.1  / Django 5.2.9 / DDT 6.1.0
1. Run the server `uv run manage.py runserver` and a single DDT setting:
```
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.profiling.ProfilingPanel',
    ]
```
2. Open a page and right away quickly do a hard refresh (cmd+shift+R or ctrl+shift+R)
3. See the traceback:

```
Traceback (most recent call last):
  File "/Users/amureki/dev/voiio/platform/.venv/lib/python3.14/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/amureki/dev/voiio/platform/.venv/lib/python3.14/site-packages/debug_toolbar/middleware.py", line 137, in __call__
    response = toolbar.process_request(request)
  File "/Users/amureki/dev/voiio/platform/.venv/lib/python3.14/site-packages/debug_toolbar/panels/profiling.py", line 163, in process_request
    return self.profiler.runcall(super().process_request, request)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amureki/.local/share/uv/python/cpython-3.14.1-macos-aarch64-none/lib/python3.14/cProfile.py", line 110, in runcall
    self.enable()
    ~~~~~~~~~~~^^
ValueError: Another profiling tool is already active
```

I think, having some side requests (async HTML/JS fetch of static/media) is increasing the chances of seeing this error.

**Comment by Mike3285** [comment]
It's still happening with 
Django==5.2.8
django-debug-toolbar==6.2.0

```manage.py runserver 8000 --nothreading````

`nothreading` seems to fix, but the slow page I am trying to profile becomes irresponsive
