### ISSUE TITLE
ImportError in 4.4.6 release cannot import name '_HTML_TYPES' from 'debug_toolbar.middleware'

### ISSUE THREAD

**Issue by ldynia** [jazzband/django-debug-toolbar#1963]
```
  File "/home/nonroot/.local/lib/python3.11/site-packages/strawberry_django/middlewares/debug_toolbar.py", line 11, in <module>
    from debug_toolbar.middleware import _HTML_TYPES, get_show_toolbar  # noqa: PLC2701
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name '_HTML_TYPES' from 'debug_toolbar.middleware' (/home/nonroot/.local/lib/python3.11/site-packages/debug_toolbar/middleware.py)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nonroot/.local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/home/nonroot/.local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/nonroot/.local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/nonroot/.local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/nonroot/.local/lib/python3.11/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/config/asgi.py", line 19, in <module>
    application_django = get_asgi_application()

```

**Comment by matthiask** [comment]
Hi

Sorry for breaking strawberry-django. However, they relied on an internal attribute of the toolbar which isn't documented and which obviously is private (the name starts with an underscore).

You could add something like this to your code as a temporary workaround and ensure that this runs before strawberry-django is imported:

```python
from debug_toolbar import middleware, utils
middleware._HTML_TYPES = utils._HTML_TYPES
```

That's as terrible as it looks, but it will allow you to use the newest version of the toolbar.

**Comment by tim-schilling** [comment]
Closing this because https://github.com/strawberry-graphql/strawberry-django/issues/586 has addressed it.
