### ISSUE TITLE
Python 3.12: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by jedie** [jazzband/django-debug-toolbar#1985]
I get the error below, with this:

* `Python 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0] on linux`
* `django-debug-toolbar==4.4.6`

```
Traceback (most recent call last):
  File "/home/jens/toniecloud/foobar/manage.py", line 21, in <module>
    main()
  File "/home/jens/toniecloud/foobar/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/jens/.local/share/virtualenvs/foobar--99rkNFF/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/jens/.local/share/virtualenvs/foobar--99rkNFF/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/jens/.local/share/virtualenvs/foobar--99rkNFF/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jens/.local/share/virtualenvs/foobar--99rkNFF/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jens/.local/share/virtualenvs/foobar--99rkNFF/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jens/.local/share/virtualenvs/foobar--99rkNFF/lib/python3.12/site-packages/drf_yasg/__init__.py", line 2, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

Work-a-round: Install `setuptools` into the used venv...

**Comment by matthiask** [comment]
Hi

Not sure why you think this is an issue with django-debug-toolbar? `pkg_resources` is imported by [drf-yasg](https://pypi.org/project/drf-yasg/), so the issue is with that library. It seems to be a known issue, see https://github.com/axnsan12/drf-yasg/issues/875

Thanks!

**Comment by jedie** [comment]
Oh, sorry ;)
