### ISSUE TITLE
Support insertion in StreamingHttpResponse

### ISSUE THREAD

**Issue by sirex** [jazzband/django-debug-toolbar#359]
Since Django 1.5 StreamingHttpResponse is introduced, this response class does not have content attribute, django-debug-toolbar middleware should be aware of that.

Now I get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/sirex/.buildout/eggs/Django-1.5-py2.7.egg/django/contrib/staticfiles/handlers.py", line 72, in __call__
    return self.application(environ, start_response)
  File "/home/sirex/.buildout/eggs/Django-1.5-py2.7.egg/django/core/handlers/wsgi.py", line 255, in __call__
    response = self.get_response(request)
  File "/home/sirex/.buildout/eggs/Django-1.5-py2.7.egg/django/core/handlers/base.py", line 187, in get_response
    response = middleware_method(request, response)
  File "/home/sirex/.buildout/eggs/django_debug_toolbar-0.9.4-py2.7.egg/debug_toolbar/middleware.py", line 131, in process_response
    smart_unicode(response.content),
  File "/home/sirex/.buildout/eggs/Django-1.5-py2.7.egg/django/http/response.py", line 341, in content
    "Use `streaming_content` instead." % self.__class__.__name__)
AttributeError: This StreamingHttpResponse instance has no `content` attribute. Use `streaming_content` instead.
```

I use Django 1.5 and django-debug-toolbar 0.9.4.

**Comment by jowolf** [comment]
I'm still getting this on Django 1.7.7 and DjDT 1.3.0:

"This FileResponse instance has no `content` attribute. Use `streaming_content` instead."

    Traceback:
    File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
    204.                 response = middleware_method(request, response)
    File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/middleware.py" in process_response
    94.             new_response = panel.process_response(request, response)
    File "/usr/local/lib/python2.7/dist-packages/w3c_validator/panels.py" in process_response
    38.         self.validator.validate_source(response.content)
    File "/usr/local/lib/python2.7/dist-packages/django/http/response.py" in content
    377.             "Use `streaming_content` instead." % self.__class__.__name__)
    
    Exception Type: AttributeError at /assets/css/skin.css
    Exception Value: This FileResponse instance has no `content` attribute. 
    Use `streaming_content` instead.

Is there a config change I need to make, or a workaround?

JJW
