### ISSUE TITLE
check_middleware does not work with function in MIDDLEWARE

### ISSUE THREAD

**Issue by pm13** [jazzband/django-debug-toolbar#874]
With Django 1.10 MIDDLEWARE can contain functions (first example in https://docs.djangoproject.com/en/1.10/topics/http/middleware/#writing-your-own-middleware). But function is_middleware_class called by check_middleware (https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/apps.py#L66) expects that middleware is class.

Possible change - current code:
return issubclass(middleware_cls, middleware_class)

working code:
return isinstance(middleware_cls, type) and issubclass(middleware_cls, middleware_class)

**Comment by SalahAdDin** [comment]
Have to see this problem with that ever i put `debug_tooblar` middleware i have this error:
```bash
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/uzman/uzman/uzman/wsgi.py", line 18, in <module>
    application = get_wsgi_application()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by SalahAdDin** [comment]
No, i'm sorry, the problem is with current version, it is solved with the current master version, which isn't release yet!

**Comment by Jastrzebowski** [comment]
@SalahAdDin any date for 1.6 release?

**Comment by SalahAdDin** [comment]
which 1.6? Wagtail? I have these error in wagtail. 
Debub toolbar haven't any new release.

**Comment by matthiask** [comment]
The PR #879 hopefully fixes this.
